name: sketch
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^7.7.0
  injectable: ^2.4.2
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.4
  image: ^4.5.4
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  provider: ^6.1.5
  share_plus: ^10.0.0
  url_launcher: ^6.3.1
  zoom_tap_animation: ^1.1.0
  path: ^1.9.0
  in_app_review: ^2.0.10
  device_info_plus: ^9.0.0
  image_gallery_saver: '^2.0.3'
  overlay_support: ^2.1.0
  image_cropper: ^8.0.1
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  injectable_generator: ^2.6.1
  flutter_launcher_icons: ^0.14.2


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"
  adaptive_icon_foreground: "assets/icon2.png"
  adaptive_icon_background: "assets/icon3.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

